### ISSUE TITLE
标量对向量的求导问题

### ISSUE THREAD

**Issue by hatleon** [soloice/Matrix_Derivatives#1]
你好，问一下，实值函数对向量求导有哪些运算法则，谢谢！

（1）你好，pdf P11页有提到实值函数对向量的求导内容。目前我想对图片里的w求导，推导过程没有明确的方向，因为不知道向量求导法则。
![vector](https://user-images.githubusercontent.com/25217721/55771733-d9bdf580-5abb-11e9-92ae-58d0ed6bb1da.PNG)

（2）再比如我想对w求导，我用“变量多次出现的求导法则”（第6页）进行向量求导，但是括号能随便去除吗？迹技巧好像对向量求导没用。
![w](https://user-images.githubusercontent.com/25217721/55771954-ba739800-5abc-11e9-97b0-6df67a118270.PNG)

（3）P17 提到实数与一堆矩阵、向量作数乘时可以随意移动位置。这个对向量求导能用吗？

**Comment by soloice** [comment]
好久没上 github 了。向量就是 n*1 的矩阵，利用你提到的 (3) 把你的目标函数写成 f(h, t) = ||(h - ww^Th + d  - (t - ww^Tt))||_2^2，然后公式里所有计算都是矩阵乘法，按文档里的公式算就行了。
好像在知乎上回复过你。
